wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1632735766
    t:
      3:
      - 2
      - 12
      4: 3.8.3
      5: 0.12.2
      8:
      - 1
      - 3
      - 5
