wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1633261338
    t:
      1:
      - 1
      2:
      - 1
      - 11
      3:
      - 2
      4: 3.8.3
      5: 0.12.2
      8:
      - 3
      - 5
training.dropout:
  desc: null
  value: 0.32054726069145767
training.optimizer.learn_rate:
  desc: null
  value: 0.0023063641528322564
